### ISSUE TITLE
Cannot reliably pair bots once they have paired to a phone

### ISSUE THREAD

**Issue by scottcreynolds** [Jewelbots/jewelbot-firmware#72]
After pairing a bot with a phone app, attempting to pair two bots leaves them permanently in blinking-white mode.

power-cycling the bot after pairing with a phone seems to help but obviously that's not a great solution

**Comment by davison-sm** [comment]
Appears to be fixed in commit 50578ac

Much of the improvement likely is owed to the previous rewrite of the friend pairing process.  Work here ensures the transmit powers and bluetooth statuses are set correctly when exiting a pairing, but not bonded, connection.
